### ISSUE TITLE
Automatically updating

### ISSUE THREAD

**Issue by AnnWX** [SteepAtticStairs/AtticRadar#2]
I am wondering if you can make it so AtticRadar can automatically update warnings and radar instead of having to refresh the page.

**Comment by SteepAtticStairs** [comment]
Thanks for opening the issue. I've already attempted to add a feature that will auto-update the radar data: [app/radar/misc/autoUpdate.js](https://github.com/SteepAtticStairs/AtticRadar/blob/main/app/radar/misc/autoUpdate.js) If you look in the console, you can see it will attempt to do this every 15 seconds. However, I'm running into an issue with the browser caching the file, which makes it so that AtticRadar doesn't always fetch the most up-to-date file listing all of the radar data. Once I get this issue solved, I can then easily add the auto-updating feature for alert polygons.

**Comment by SteepAtticStairs** [comment]
The radar data should now auto-update as of [823fee6](https://github.com/SteepAtticStairs/AtticRadar/commit/823fee6055e993f0748a1c0e0fed59c3a61b9b38). I'll work on doing the same for alert polygons.

**Comment by wilburcoding** [comment]
Any idea when auto-updating alert polygons will be available? @SteepAtticStairs

**Comment by SteepAtticStairs** [comment]
@wilburcoding Thanks for showing interest in AtticRadar!

Right now, I'm working on implementing some new NEXRAD parsers that I transcribed from python to javascript, which requires some extensive rewriting of the codebase. Plus, I'm doing some general-purpose refactoring of the code, as it is very messy in its current state.

However, the next item on my to-do list is indeed implementing an auto-updater for the alerts. This, unfortunately, also requires almost a complete rewrite of the alerts system, since I discovered too late that I had initially written it in a way that was unfriendly towards future modifications.

Rest assured that big things are in store for this project, and your request is among them!

If I had to give a time estimate for when this feature will become available, I would hazard a guess of within a month, but I do have school and SAT studying coming up, so I'm not sure how open my schedule will be to work on AtticRadar. However, I enjoy this project immensely, and I cherish the time that I am granted to work on it.

God bless you, friend - and please reach out with any further concerns!
- Andrew

**Comment by wilburcoding** [comment]
Hi,
No worries! I am certainly looking forward to these new changes!

**Comment by SteepAtticStairs** [comment]
This has already been implemented, but I forgot to close the issue.
