### ISSUE TITLE
Radar Opacity

### ISSUE THREAD

**Issue by AnnWX** [SteepAtticStairs/AtticRadar#7]
So I noticed Attic Radar got updated and i noticed how the radar is overlaying other layers. Can you add a feature to allow users to adjust the opacity of different layers. 
![Screenshot 2023-06-06 5 05 25 PM](https://github.com/SteepAtticStairs/AtticRadar/assets/86276545/42b6a015-ac39-4571-a869-4de8f1d0811c)

**Comment by SteepAtticStairs** [comment]
Thanks for the issue!

That would be a rather immense task, as most of the layers (e.g. metars, surface fronts) are directly drawn on by the Mapbox API, so you would have to do some wrangling to set a universal opacity per layer. Plus, the added time spent creating an entire HTML menu for that isn't worth it at this time, in my opinion.

However, I do see that the radar plot is overlaying the metars, and that isn't what's supposed to happen. I just pushed the commit [`295fa4f`](https://github.com/SteepAtticStairs/AtticRadar/commit/295fa4f295322ae894148fa7e333f558e680c087), which should make the order go, from back to front:

radar -> metars -> surface fronts

In the future, I might create a menu where you can adjust the order of the `setLayerOrder()` function, but for now, I'll leave this issue open so that you can let me know if you agree with the fixed layer order.

Thanks!
