### ISSUE TITLE
Question about G-Tag and fork

### ISSUE THREAD

**Issue by WXFanatics** [SteepAtticStairs/AtticRadar#9]
Hey! 

I love the project you've made thus far and it's really helped me learn quite a lot just by watching you make it over time. I have a personal fork of it and I want to make sure I am respecting your project, which leads me to my question.

It was my understanding in the past that the origin of a google tag shouldn't be spread across multiple uncontrolled sites. Am I incorrect in that assumption? I tried to look around but couldn't find anything definitive. Was I incorrect for removing it? https://github.com/WXFanatics/AtticRadar/commit/ee667edfe291a29953c97b58e5d8e4e296985b14

Personally I only run it on a local raspberry pi and only make a few changes to my styling preferences here and there. If someone else were to use it though, I'd want to make sure I am respecting your project to the fullest.

Thanks!

**Comment by SteepAtticStairs** [comment]
@WXFanatics

Thanks for reaching out! I do believe that you're right that google tags should really only be used on the parent website. I think the protocol for this case is creating your own tag, if you wish to track your own website visits. But, since you said you're only running it locally on a Raspberry Pi, I don't think that would be very useful for you.

As for the question about your fork, please feel free to continue  doing what you're doing! I don't have a problem with it, and I do appreciate that you've given me credit, as I can see in the README. I hope to add some more settings options in the future, where you can choose your own radar colortables or alert colors, but in the meantime, I encourage you to continue with your fork.

- Andrew
